---
name: "release"
on:
  push:
    tags:
      - 'release/**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/
      - name: install cachix
        uses: cachix/cachix-action@v10
        with:
          name: canonical-llc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: set supported systems
        run: echo $(uname -m)-$(uname -s) | tr '[:upper:]' '[:lower:]' | sed -E 's/^(.*)$/[ "\1" ]/' | tee supported-systems.nix
      - name: set version
        run: echo "RELEASE_VERSION=$(echo $GITHUB_REF_NAME | cut -f 2 -d /)" >> $GITHUB_ENV
      - name: build
        run: nix flake check --print-build-logs
      - name: build release
        run: nix build --print-build-logs -f release.nix --argstr version ${{ env.RELEASE_VERSION }}
      - name: copy tarball
        run: cp --no-preserve=all --dereference result voomio-bulk-purchase-${{ env.RELEASE_VERSION }}.tar.gz
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: voomio-bulk-purchase-${{ env.RELEASE_VERSION }}.tar.gz

